### ISSUE TITLE
Martini Polyelectrolytes

### ISSUE THREAD

**Issue by martinvoegele** [fgrunewald/Martini_PolyPly#14]
Hey, I recently stumbled upon this extremely helpful project. I was wondering whether it would be a large effort to include also the Martini polyelectrolytes: http://cgmartini.nl/index.php/polyelectrolytes. If necessary, I can offer my help in implementing this feature.

**Comment by fgrunewald** [comment]
Hey Martin, 
In fact it is the plan to include all MARTINI polymers in the library for the itp generator as well as make sure that a "proper" structure can be generated. The later is currently a problem with the electrolytes. The program has no Coulomb potential, which means the structures are somewhat too coiled up and the algorithm crashes after 8, 10 repeat units. However, we are on it, so it shouldn't be too long until they are implemented.

**Comment by fgrunewald** [comment]
@martinvoegele PSS & PDAMA are now part of the library. Can you check that the generated itp files are correct. I think they should be but I had to flip the order of the atoms for PSS, because polystyrene only works with the structure generator when the order is reversed. This has to do with the fact that in MARTINI PS the first bead is the a backbone bead, which is located between the first and the second ring. The program, however, only works when first the ring is generated and then the bead connecting that ring with the next one. This is due to the search algorithm. Long story short, I'd be happy if you can check that the itp is correct. For the structure generator the improper dihedrals are still missing, so that won't work just yet.

**Comment by fgrunewald** [comment]
oh yes and you can install the latest version using pip pip install git+https://github.com/fgrunewald/Martini_PolyPly.git#polyply

**Comment by martinvoegele** [comment]
@fgrunewald Awesome!
I checked the itp files. 
For PSS, I found constraints, bonds, and dihedrals to be correct. There are some problems with the angles. Here I tried to translate the old numbers directly to the new ones and found a different result (I made an according fork).
PDADMA is perfect as is.

**Comment by fgrunewald** [comment]
@martinvoegele Yes you're right! Probably wasn't such a good idea to do this yesterday night. I edited the files, so now it should be fine. But just to be sure I'd say have another look. Other than that feedback  anything  is always appreciated! I'll close the issue when the structure generation also works.

**Comment by martinvoegele** [comment]
@fgrunewald To me the itp file looks fine now. 
I might do a full test with structure + topology when everything is set.

**Comment by fgrunewald** [comment]
@martinvoegele since a couple of weeks polyply also has electrostatics and I just implemented improper dihedrals. If you could test it, I'd appreciate it and if you've any problems let me know

**Comment by martinvoegele** [comment]
@fgrunewald Thanks for letting me know. Here is my first experience:

I tried
`polyply -polymer PSS -n_mon 10 -o PSS.itp -name PSS`
and got the following error message:

> No second terminal found. Are you sure you want to leave the polymer unterminated?

However, the generated itp file seems to be fine.

Then I wanted to build a structure using 
`polyply -env vac -s PSS.itp -o PSS.gro -name PSS`
but I got

> polyply: error: ambiguous option: -s could match -sys, -spacing, -softness, -sol

I suppose the options have changed compared to the readme file. What would be the correct command?

**Comment by fgrunewald** [comment]
@martinvoegele 

yes the first thing is just a warning. That should probably be pointed out. 

concerning the second error, it has indeed changed now it should be -p as you would do in GROMACS. When you execute polyply -h it should show all the options. But you'll need to feed it a topology file not only the itp. Something like

#include martini.itp
#include PSS.itp 
[ system ]
test
[ molecules ]
PSS 1

Of course you'll also need to update to the latest version. In case you did not install it using 'pip3 install -e',  you'll probably have to delete it first and reinstall.

**Comment by martinvoegele** [comment]
All right, thanks. 

Now I tried 
```
polyply -env vac -p mytopol.top -o PSS.gro -name PSS
```
using _mytopol.top_ as follows
```
#include martini_v2.2P_PS_corr.itp
#include PSS.itp
[ system ]
test
[ molecules ]
PSS 1
```
with the itp file from [here](https://github.com/martinvoegele/martini-polyelectrolytes/blob/master/martini_v2.2P_PS_corr.itp).

Here I encounter a problem when reading the file:

> File "/home/martin/Martini_PolyPly/polyply/structure_tool/force_field_tools.py", line 142, in read_itp
    nonbond_params.update({(atom1, atom2): {'sigma':nfl(sigma), 'epsilon':nfl(epsilon)}})
ValueError: invalid literal for float(): 0.21661E-03;

Maybe there are some non-printing characters in the itp file that should be taken care of when reading. 

With _martini_v2.2P.itp_ from the Martini homepage, I get a different one

> File "/home/martin/Martini_PolyPly/polyply/structure_tool/force_field_tools.py", line 137, in read_itp
    n, typ, resnr, res, atom, cgnr, charge, mass = line.replace('\n', '').split()[0:8]
ValueError: need more than 7 values to unpack

**Comment by fgrunewald** [comment]
Hi, 

Well that's much more struggle than I expected. Sorry for that but GROMACS top and itps are not very easy to parse because there is a large number of variables for instance mass, which can be defined in several places and they have a particular hierarchy. That's among other things why for instance MDAnalysis uses tpr files. It's not an excuse but rather I'd like to point out how valuable these tests are, because as you can imagine we mainly use the same itp file. 

Anyways, concerning your problems the first one results from the comment character (;) being not separated by space from the the C12 value. Thus it tries to read it as ''0.21661E-03;" which is not a float. Putting a space should resolve this problem. The later originates from the water not having the mass defined in the martini itp file. Plus the '[' character of the section is not separated from the section title (i.e. [angles] is not good but rather [ angles ])  If you fix either it should work. But for the sake of not putting you through more trouble enclosed a working polarizable itp file based on the one from your directory.  

[PSS.zip](https://github.com/fgrunewald/Martini_PolyPly/files/1844381/PSS.zip)

I would say the output structure looks shitty but it minimizes quite well. If you use VMD to visualize it might be that depending on the VMD version have to save the .gro file again. Seems a random VMD bug. Anything else works just fine.

**Comment by martinvoegele** [comment]
Ah, I see the problem.  
I ran it again with the files you provided and it worked as you described - including the VMD bug. :-)

**Comment by fgrunewald** [comment]
Perfect! Then I'll close the issue.
